- name: Install required apt packages
  become: yes
  package: 
    name:
      - docker
      - docker-compose
    state: latest
- name: Install required pip packages
  become: yes
  pip: 
    name:
      - docker-py