- name: Install required apt packages
  become: yes
  apt:
    pkg: 
    - docker
    - docker-compose
    state: latest
  update_cash: yes
- name: Install required pip packages
  pip: 
    name:
      - docker-py