- name: Install required apt packages
  become: yes
  apt: 
    update_cache: yes
    pkg:
      - docker
      - docker-compose
      - python
      - python3-pip
      - avahi-daemon


# - name: Install PIP Install script
#   become: yes
#   get_url:
#     url: https://bootstrap.pypa.io/get-pip.py
#     dest: /opt/get-pip.py
# - name: Install PIP
#   become: yes
#   shell: python /opt/get-pip.py
- name: Install required pip packages
  become: yes
  pip: 
    name:
      - docker
      - docker-compose
