---
- name: Add libpq-dev to system prerequisites
  set_fact:
    zammad_system_prerequisites_packages: "{{ zammad_system_prerequisites_packages | default([]) + [ 'libpq-dev' ] }}"
  when: zammad_db_postgresql

- name: Add libmysqlclient-dev to system prerequisites
  set_fact:
    zammad_system_prerequisites_packages: "{{ zammad_system_prerequisites_packages | default([]) + [ 'libmysqlclient-dev' ] }}"
  when: zammad_db_mysql

- name: Add nginx to system prerequisites
  set_fact:
    zammad_system_prerequisites_packages: "{{ zammad_system_prerequisites_packages | default([]) + [ 'nginx' ] }}"
  when: zammad_install_nginx

- name: Install system prerequisites
  package:
    name: "{{ item }}"
    state: present
  become: yes
  become_method: sudo
  become_user: root
  with_items: "{{ zammad_system_prerequisites_packages }}"

- name: requirements for installing gems
  apt:
    name: {{ item }}
  with_items:
    - ruby
    - ruby-dev
    - make

- name: install gem with proper $PATH
  gem:
    name: bundler
    user_install: no