---
- name: Ensure zammad group exists
  group:
    name: "{{ zammad_group }}"
    state: present
  become: yes
  become_method: sudo
  become_user: root

- name: Add zammad user
  user:
    name: "{{ zammad_user }}"
    group: "{{ zammad_group }}"
    uid: 1040
    shell: /bin/bash
    state: present
  become: yes
  become_method: sudo
  become_user: root