---
- name: Install nginx configuration
  copy:
    src: /opt/zammad/contrib/nginx/zammad.conf
    dest: /etc/nginx/sites-available/zammad.conf
    remote_src: yes
    mode: 0644
  notify:
    - restart nginx
  when: zammad_configure_nginx

- name: Link nginx vhost configuration
  file:
    src: /etc/nginx/sites-available/zammad.conf
    dest: /etc/nginx/sites-enabled/zammad.conf
    owner: root
    group: root
    state: link
  notify:
    - restart nginx
  when: zammad_configure_nginx

- name: Remove nginx default vhost
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx
  when: zammad_remove_nginx_default_vhost

- name: Remove nginx default vhost
  file:
    path: /etc/nginx/sites-enabled/default.conf
    state: absent
  notify:
    - restart nginx
  when: zammad_remove_nginx_default_vhost