---
- hosts: localhost
  vars_prompt:
    - name: ip
      prompt: What is the ip of ZAMMAD?
      private: no
      default: "192.168.44.159"
    - name: username
      prompt: What is the username?
      private: no
      default: "student" 
    - name: password
      prompt: What is the password?
      private: no
      default: "student"
  tasks:
    - name: Add Dynamic host
      add_host:
        name: '{{ ip }}'
        groups: dynamic_zammad
        ansible_user: "{{ username }}"
        ansible_password: "{{ password }}"
        ansible_become_pass: "{{ password }}"
- hosts: dynamic_zammad
  tasks:
    - name: Change Hostname filie
      become: yes
      shell: hostnamectl set-hostname Zammad
    
    - name: Change hosts file
      become: yes
      shell: sed -i '2 c 127.0.0.1    Zammad' /etc/hosts
      args:
        warn: false
    - name: Restart server
      become: yes
      reboot:
      
    - include: Linux/Zammad/00-zammad_install_packages.yml
      become: yes
      become_method: sudo
      become_user: root

    - include: Linux/Zammad/01-zammad_clone_repos.yml
      become: yes
      become_method: sudo
      become_user: root

    - include: Linux/Zammad/02-zammad_install_containers.yml
      become: yes
      become_method: sudo
      become_user: root
