---
- hosts: domain_controller
  tasks:
    - name: Create download folder
      win_file:
        path: C:\\ProgramData\\FreeFloat
        state: directory
        
    - name: Download freefloat zip
      win_get_url:
        url: https://www.exploit-db.com/apps/687ef6f72dcbbf5b2506e80a375377fa-freefloatftpserver.zip
        dest: C:\ProgramData\FreeFloat\freefloat.zip

    - name: Unzip file
      win_unzip:
        src: C:\ProgramData\FreeFloat\freefloat.zip
        dest: C:\ProgramData\FreeFloat

    - name: Move file to startup folder
      win_copy:
        remote_src: yes
        src: C:\ProgramData\FreeFloat\Win32\FTPServer.exe
        dest: 'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\StartUp\\FTPServer.exe'

    - name: Create a start on boot scheduled task
      win_scheduled_task:
        name: FreeFloat ftp server
        description: Start the ftp server oon boot
        actions:
        - path: C:\ProgramData\FreeFloat\Win32\FTPServer.exe
        logon_type: password
        password: 'Letmein123!'
        username: DEMO\Student
        triggers:
        - type: boot

    - name: Reboot server to start ftpserver
      win_reboot: