---
- name: Setup Ticketing system
  hosts: zammad
  
  tasks:
    
    - include: Linux/Zammad/00-zammad_clone_repos.yml
      become: yes
      become_method: sudo
      become_user: root

    - include: Linux/Zammad/01-zammad_install_containers.yml
      become: yes
      become_method: sudo
      become_user: root