---
- hosts: localhost
  vars_prompt:
    - name: ip
      prompt: What is the ip of SIEM?
      private: no
      default: "192.168.44.158"
    - name: username
      prompt: What is the username?
      private: no
      default: "student" 
    - name: password
      prompt: What is the password?
      private: no
      default: "student"
  tasks:
    - name: Add Dynamic host
      add_host:
        name: '{{ ip }}'
        groups: dynamic_siem
        ansible_user: "{{ username }}"
        ansible_password: "{{ password }}"
        ansible_become_pass: "{{ password }}"
- hosts: dynamic_siem
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Change Hostname file
      become: yes
      shell: hostnamectl set-hostname SIEM
    - name: Change hosts file
      become: yes
      shell: sed -i '2 c 127.0.0.1 SIEM' /etc/hosts
      args:
        warn: false
    
    - name: Restart server
      become: yes
      reboot:
    
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'make', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'docker-compose']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name:  remove docker dir if it already exists
      file:
          state: absent
          path: /opt/wazuh-docker

    - name: pull docker wazuh docker repo with Elasticsearch, Kibana and Wazuh-Manager
      become: yes
      git: 
       repo: https://github.com/wazuh/wazuh-docker.git
       dest: /opt/wazuh-docker
       update: yes  
    
    - name: update .env file and change password
      copy:
         dest: /opt/wazuh-docker/.env
         content: |
          API_USERNAME="admin"
          API_PASSWORD="blue_team_awesome"

    - name: add elasticsearch memory necessary setting
      become: true
      command: sysctl -w vm.max_map_count=262144

    - name: start elk server
      args:
        chdir: /opt/wazuh-docker
      command: docker-compose up -d
          
    # Copy and place the decoder and rules files for the Wazuh Manager into Docker
    - name: create temp folder
      become: yes
      shell: mkdir /opt/wazuh-docker/temp
    - name: copy decoder file
      become: yes
      copy: 
        src: /opt/RTvsBT/AnsiblePlaybooks/assets/WazuhManagerAssets/local_decoder.xml
        dest: /opt/wazuh-docker/temp/local_decoder.xml
    - name: copy rules file
      become: yes
      copy:
        src: /opt/RTvsBT/AnsiblePlaybooks/assets/WazuhManagerAssets/local_rules.xml
        dest: /opt/wazuh-docker/temp/local_rules.xml
    - name: copy ossec.conf file
      become: yes
      copy:
        src: /opt/RTvsBT/AnsiblePlaybooks/assets/WazuhManagerAssets/ossec.conf
        dest: /opt/wazuh-docker/temp/ossec.conf
    - name: copy agent.conf
      become: yes
      copy:
        src: /opt/RTvsBT/AnsiblePlaybooks/assets/WazuhManagerAssets/agent.conf
        dest: /opt/wazuh-docker/temp/agent.conf
    - name: copy decoder file into docker
      become: yes
      shell: docker cp /opt/wazuh-docker/temp/local_decoder.xml wazuh-docker_wazuh_1:/var/ossec/etc/decoders/local_decoder.xml
    - name: copy rules file into docker
      become: yes
      shell: docker cp /opt/wazuh-docker/temp/local_rules.xml wazuh-docker_wazuh_1:/var/ossec/etc/rules/local_rules.xml
    - name: copy ossec.conf into docker
      become: yes
      shell: docker cp /opt/wazuh-docker/temp/ossec.conf wazuh-docker_wazuh_1:/var/ossec/etc/ossec.conf
    - name: copy agent.conf into docker
      become: yes
      shell: docker cp /opt/wazuh-docker/temp/agent.conf wazuh-docker_wazuh_1:/var/ossec/etc/shared/default/agent.conf
    - name: restart wazuh-manager container
      become: yes
      shell: docker restart wazuh-docker_wazuh_1
