---
- hosts: Defensie_Web01
  tasks:
    - name: Install dependencies
      become: yes
      apt:
        pkg:
        - php-apcu
        - apache2
        - mysql-server
        - php-mysqli
        - libapache2-mod-php
    - name: Change Hostname filie
      become: yes
      shell: hostnamectl set-hostname Defensie-Web01
    
    - name: Change hosts file
      become: yes
      warn: false
      shell: sed -i '2 c 127.0.0.1    Defensie-Web01' /etc/hosts
      args:
        warn: false
    - name: Move the webserver files
      become: yes
      copy:
        owner: www-data
        src: ~/RTvsBT/VulnerableWebsite/
        dest: /var/www/html/
    - name: Remove default apache page.
      become: yes
      file:
        path: /var/www/html/index.html
        state: absent
    - name: seed the database
      become: yes
      shell: mysql < /var/www/html/db.sql
#    - name: Change to static ip
    
    - name: Patch apparmor
      become: yes
      lineinfile:
        path: /etc/apparmor.d/usr.sbin.mysqld
        insertbefore: '^}'
        line: '   /var/www/html/** rw,' 
    - name: Patch mysqld.cnf
      become: yes
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertbefore: '^secure_file_priv='
        line: 'secure_file_priv=""' 
    - name: change folder permissions
      become: yes
      file: 
        path: /var/www/html
        mode: '777'
    - name: add www-data to the mysql group
      become: yes
      shell: usermod -a -G mysql www-data
    
    - name: Restart server
      become: yes
      reboot:
