
---
- hosts: localhost
  vars_prompt:
    - name: ip
      prompt: What is the ip of SURICATA?
      private: no
      default: "192.168.44.152"
    - name: username
      prompt: What is the username?
      private: no
      default: "student" 
    - name: password
      prompt: What is the password?
      private: no
      default: "student"
  tasks:
    - name: Add Dynamic host
      add_host:
        name: '{{ ip }}'
        groups: dynamic_suricata
        ansible_user: "{{ username }}"
        ansible_password: "{{ password }}"
        ansible_become_pass: "{{ password }}"
- hosts: dynamic_suricata
  tasks:
    - name: Error message
      debug:
        msg: Installer not found.
