---
- hosts: Defensie_Web01
  tasks:
    - name: Install dependencies
      become: yes
      apt:
        pkg:
        - php-apcu
        - apache2
        - mysql-server
        - php-mysqli
        - libapache2-mod-php
        - curl
        - avahi-daemon
    - name: Change Hostname filie
      become: yes
      shell: hostnamectl set-hostname Defensie-Web01
    
    - name: Change hosts file
      become: yes
      shell: sed -i '2 c 127.0.0.1    Defensie-Web01' /etc/hosts
      args:
        warn: false
    - name: Move the webserver files
      become: yes
      copy:
        owner: www-data
        src: /opt/RTvsBT/VulnerableWebsite/
        dest: /var/www/html/
    - name: Remove default apache page.
      become: yes
      file:
        path: /var/www/html/index.html
        state: absent
    - name: seed the database
      become: yes
      shell: mysql < /var/www/html/db.sql
#    - name: Change to static ip
    
    - name: Patch apparmor
      become: yes
      lineinfile:
        path: /etc/apparmor.d/usr.sbin.mysqld
        insertbefore: '^}'
        line: '   /var/www/html/** rw,' 
    - name: Patch mysqld.cnf
      become: yes
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertbefore: '^secure_file_priv='
        line: 'secure_file_priv=""' 
    - name: change folder permissions
      become: yes
      file: 
        path: /var/www/html
        mode: '777'
    - name: add www-data to the mysql group
      become: yes
      shell: usermod -a -G mysql www-data
    
# Setup and install Wazuh-Agent
    - name: Get GPG key for wazuh
      become: yes
      shell: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
    - name: Add wazuh repo to apt list
      become: yes
      shell: echo "deb https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
    - name: Update apt & install Wazuh
      become: yes
      apt:
        name: wazuh-agent
        update_cache: yes
    - name: Wazuh configuration
      become: yes
      replace:
        path: /var/ossec/etc/ossec.conf
        regexp: 'MANAGER_IP'
        replace: '192.168.2.181'
    - name: Reload daemon for wazuh
      become: yes
      shell: systemctl daemon-reload
    - name: Enable wazuh for next system start
      become: yes
      shell: systemctl enable wazuh-agent
    #- name: Start wazuh
    #  become: yes
    #  shell: systemctl start wazuh-agent

# Setup and install Suricata
    - name: Install dependencies
      become: yes
      apt:
        pkg:
        - rustc
        - cargo
        - make
        - libpcre3
        - libpcre3-dbg
        - libpcre3-dev
        - build-essential
        - autoconf
        - automake
        - libtool
        - libpcap-dev
        - libnet1-dev
        - libyaml-0-2
        - libyaml-dev
        - zlib1g
        - zlib1g-dev
        - libcap-ng-dev
        - libcap-ng0
        - make
        - libmagic-dev
        - libjansson-dev
        - libjansson4
        - pkg-config
        - python3-pip
    - name: Pip install Suricata-update
      become: yes
      shell: pip3 install --upgrade suricata-update
    - name: Create symlink
      become: yes
      shell: ln -s /usr/local/bin/suricata-update /usr/bin/suricata-update
    - name: Download latest version of Suricata
      become: yes
      shell: wget https://www.openinfosecfoundation.org/download/suricata-6.0.1.tar.gz -O /opt/suricata-6.0.1.tar.gz
    - name: Extract the downloaded files
      become: yes
      shell: tar -xvzf /opt/suricata-6.0.1.tar.gz
    - name: Change directory and configure it
      become: yes
      shell: ./configure --enable-nfqueue --prefix=/usr --sysconfdir=/etc --localstatedir=/var
      args:
        chdir: /opt/suricata-6.0.1
    - name: Make
      become: yes
      shell: make
      args:
        chdir: /opt/suricata-6.0.1
    - name: Make install
      become: yes
      shell: make install-full
      args:
        chdir: /opt/suricata-6.0.1
    - name: Install all the rules
      become: yes
      shell: make install-rules
      args:
        chdir: /opt/suricata-6.0.1
    - name: Edit suricata.yaml
      become: yes
      shell: sed -i "/^ *HOME_NET/s/\[[^]]*\]/\[192.168.2.0\/24]/g" /etc/suricata/suricata.yaml
    - name: Install the suricata service
      become: yes
      copy:
        src: /opt/RTvsBT/AnsiblePlaybooks/assets/suricata/suricata.service
        dest: /etc/systemd/system/suricata.service
        
    - name: Add nmap scan 
      lineinfile:
        path: /var/lib/suricata/rules/suricata.rules
        line: alert tcp any any -> any 22 (msg:"ET SCAN Possible NMAP SSH Enumeration"; content:"get_banner";)
        create: yes
    - name: Enable wazuh for next system start
      become: yes
      shell: systemctl enable suricata
    - name: Restart server
      become: yes
      reboot:
#     - name: Start Suricata
#       become: yes
#       shell: suricata -c /etc/suricata/suricata.yaml -i ens160
