---
- hosts: Defensie_Lxd01
  tasks:
    - name: Change Hostname file
      become: yes
      shell: hostnamectl set-hostname Defensie-Lxd01
    - name: Change hosts file
      become: yes
      shell: sed -i '2 c 127.0.0.1    Defensie-Lxd01' /etc/hosts
      args:
        warn: false
    - name: Install LXD
      package:
        name: lxd
        state: present
      become: yes
    - name: Install LXD-Client
      package:
        name: lxd-client
        state: present
      become: yes
    - name: Create a user
      user: 
        name: Carl
        password: '$6$.UO2AiUW0UfQRavK$xQnMWvBJxovm8y1KHIVqtghWnZowkxftaNIhmo9.onqfvZdIE3Ae6uaddkEHEixJNgMEvjNFJqGhgGM68bdJc/'
        groups: lxd
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/carl