---
- hosts: siem
  become: true
  gather_facts: true

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'make', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'docker-compose']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name:  remove docker dir if already exist
      file:
          state: absent
          path: /home/student/wazuh-docker

    - name: pull docker wazuh docker repo with Elasticsearch, Kibana and Wazuh-Manager
      become: yes
      git: 
       repo: https://github.com/wazuh/wazuh-docker.git
       dest: /home/student/wazuh-docker
       update: yes  
    
    - name: update .env file and change password
      replace:
         path: /home/student/wazuh-docker/.env
         regexp: 'ELASTIC_PASSWORD=changeme'
         replace: ELASTIC_PASSWORD=blue_team_awesome

    - name: add elasticsearch memory necessary setting
      become: true
      command: sysctl -w vm.max_map_count=262144

    - name: start elk server
      args:
        chdir: /home/student/wazuh-docker
      command: docker-compose up -d
          
